@ChampionsDraft.API_HostAddress = https://localhost:44382

POST {{ChampionsDraft.API_HostAddress}}/cardLibrary
Accept: application/json

###

POST {{ChampionsDraft.API_HostAddress}}/card
Accept: application/json

###
