name: Build .NET app

on:
  pull_request:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  build:
    name: Build All Projects
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - ChampionsDraft.API/ChampionsDraft.API/API.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build ${{ matrix.project }} --no-restore --configuration Release